export enum IconType {
    ARROW_RIGHT = 'ARROW_RIGHT',
    ATOM = 'ATOM',
    CPU = 'CPU',
    CUBE = 'CUBE',
    MOON = 'MOON',
    SOCIAL_GITHUB = 'SOCIAL_GITHUB',
    SOCIAL_REDDIT = 'SOCIAL_REDDIT',
    SOCIAL_TWITTER = 'SOCIAL_TWITTER',
    SUN = 'SUN',
}
